# This is the main configuration file of GameBox
# For documentation beyond the inline comments, see https://hygames.co/gamebox/settings/config-file

# Settings concerning the module cloud
moduleCloud:
  # set this to false to completely disable the cloud
  enabled: true
  # Weather or not to automatically download compatible updates
  # default value for all modules
  #    this setting can be overwritten for selected modules in 'modules.yml'
  defaultAutoUpdates: false

# The language file to load messages from
languageFile: default
